-- 审批表
INSERT INTO `eb_approve` (`id`, `user_id`, `card_id`, `entid`, `name`, `icon`, `color`, `info`, `types`, `examine`, `config`, `status`, `sort`, `created_at`, `updated_at`, `deleted_at`) VALUES
(NULL, 1, 1, 1, '撤销申请', 'iconwendang11', '#FF9900', '', 11, 1, '', 1, 1, '2024-09-20 10:53:41', '2024-10-30 14:59:55', NULL);
SELECT @shenqingId := LAST_INSERT_ID();

-- 审批表单
INSERT INTO `eb_approve_form` (`id`, `user_id`, `card_id`, `approve_id`, `title`, `info`, `value`, `required`, `types`, `symbol`, `content`, `props`, `options`, `config`, `uniqued`, `sort`) VALUES
(NULL, 1, 1, 6, '提交时间', '', '', 0, 'datePicker', '', '{\"type\":\"datePicker\",\"field\":\"Feu864cy10cq1\",\"title\":\"\\u63D0\\u4EA4\\u65F6\\u95F4\",\"info\":\"\",\"props\":{\"type\":\"datetime\"},\"_fc_drag_tag\":\"datetimerange\",\"hidden\":false,\"display\":true}', '{\"type\":\"datetime\"}', '', '', '\"Feu864cy10cq1\"', 0),
(NULL, 1, 1, @shenqingId, '撤销理由', '', '', 0, 'input', '', '{\"type\":\"input\",\"field\":\"Fpad64cy113te\",\"title\":\"\\u64a4\\u9500\\u7406\\u7531\",\"info\":\"\",\"props\":{\"type\":\"textarea\"},\"_fc_drag_tag\":\"textarea\",\"hidden\":false,\"display\":true}', '{\"type\":\"textarea\"}', '', '', '\"Fpad64cy113te\"', 1);

-- 审批规则
INSERT INTO `eb_approve_rule` (`id`, `user_id`, `card_id`, `approve_id`, `range`, `abnormal`, `auto`, `edit`, `recall`, `is_transfer`, `is_sign`, `refuse`) VALUES
(NULL, 1, 1, @shenqingId, '', 0, '0', '[\"1\",\"2\"]', 0, 0, 1, '0');

-- 开放接口
INSERT INTO `eb_openapi_rule` (`id`, `pid`, `name`, `type`, `crud_id`, `method`, `url`, `path_prams`, `created_at`, `updated_at`, `get_prams`, `post_prams`, `request_data`, `response_data`) VALUES
(1, 0, '对外接口授权', 0, 0, '0', '0', '', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, NULL, NULL, NULL),
(2, 1, '授权登录', 1, 0, 'POST', 'open/auth/login', '', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, '[{\"name\":\"access_key\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"授权账号\"},{\"name\":\"secret_key\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"授权秘钥\"}]', NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\",\"children\":[{\"name\":\"token\",\"form_type\":\"string\",\"message\":\"授权凭证\"},{\"name\":\"token_type\",\"form_type\":\"string\",\"message\":\"凭证类型\"},{\"name\":\"expires_in\",\"form_type\":\"int\",\"message\":\"过期时间\"}]},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]'),
(3, 0, '客户基本信息', 0, 0, '0', '0', '', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, NULL, NULL, NULL),
(4, 3, '新增客户', 1, 0, 'POST', 'open/customer', '', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, '[{\"name\":\"customer_name\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"客户名称1\"},{\"name\":\"customer_label\",\"form_type\":\"array\",\"is_must\":false,\"message\":\"客户标签\"},{\"name\":\"customer_way\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"客户来源\"},{\"name\":\"b37a3f16\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"企业电话\"},{\"name\":\"area_cascade\",\"form_type\":\"array\",\"is_must\":false,\"message\":\"省市区\"},{\"name\":\"9bfe77e4\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"详细地址\"},{\"name\":\"customer_status\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"客户状态\"},{\"name\":\"customer_followed\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"是否关注\"}]', NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\",\"children\":[{\"name\":\"id\",\"form_type\":\"int\",\"message\":\"自增ID\"}]},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]'),
(5, 3, '修改客户', 1, 0, 'PUT', 'open/customer/{id}', '[{\"name\":\"id\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"自增ID\"}]', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, '[{\"name\":\"customer_name\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"客户名称1\"},{\"name\":\"customer_label\",\"form_type\":\"array\",\"is_must\":false,\"message\":\"客户标签\"},{\"name\":\"customer_way\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"客户来源\"},{\"name\":\"b37a3f16\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"企业电话\"},{\"name\":\"area_cascade\",\"form_type\":\"array\",\"is_must\":false,\"message\":\"省市区\"},{\"name\":\"9bfe77e4\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"详细地址\"},{\"name\":\"customer_status\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"客户状态\"},{\"name\":\"customer_followed\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"是否关注\"}]', NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\"},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]'),
(6, 3, '删除客户', 1, 0, 'DELETE', 'open/customer/{id}', '[{\"name\":\"id\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"自增ID\"}]', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, NULL, NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\"},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]'),
(7, 0, '合同', 0, 0, '0', '0', '', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, NULL, NULL, NULL),
(8, 7, '新增合同', 1, 0, 'POST', 'open/contract', '', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, '[{\"name\":\"contract_name\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"合同名称\"},{\"name\":\"contract_no\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"合同编号\"},{\"name\":\"contract_status\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"合同状态\"},{\"name\":\"contract_followed\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"是否关注\"},{\"name\":\"contract_category\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"合同分类\"},{\"name\":\"contract_price\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"合同金额(元)\"},{\"name\":\"contract_customer\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"客户名称\"},{\"name\":\"start_date\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"开始时间\"},{\"name\":\"end_date\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"结束时间\"},{\"name\":\"b3733f36\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"备注\"},{\"name\":\"signing_status\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"签约状态\"}]', NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\",\"children\":[{\"name\":\"id\",\"form_type\":\"int\",\"message\":\"自增ID\"}]},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]'),
(9, 7, '修改合同', 1, 0, 'PUT', 'open/contract/{id}', '[{\"name\":\"id\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"自增ID\"}]', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, '[{\"name\":\"contract_name\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"合同名称\"},{\"name\":\"contract_no\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"合同编号\"},{\"name\":\"contract_status\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"合同状态\"},{\"name\":\"contract_followed\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"是否关注\"},{\"name\":\"contract_category\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"合同分类\"},{\"name\":\"contract_price\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"合同金额(元)\"},{\"name\":\"contract_customer\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"客户名称\"},{\"name\":\"start_date\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"开始时间\"},{\"name\":\"end_date\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"结束时间\"},{\"name\":\"b3733f36\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"备注\"},{\"name\":\"signing_status\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"签约状态\"}]', NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\"},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]'),
(10, 7, '删除合同', 1, 0, 'DELETE', 'open/contract/{id}', '[{\"name\":\"id\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"自增ID\"}]', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, NULL, NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\"},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]'),
(11, 0, '客户联系人', 0, 0, '0', '0', '', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, NULL, NULL, NULL),
(12, 11, '新增联系人', 1, 0, 'POST', 'open/liaison', '', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, '[{\"name\":\"liaison_job\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"联系人职位\"},{\"name\":\"liaison_name\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"联系人姓名\"},{\"name\":\"liaison_tel\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"联系电话\"},{\"name\":\"e06d7153\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"性别\"},{\"name\":\"e06d7152\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"联系人邮箱\"},{\"name\":\"e06d7159\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"联系人微信\"},{\"name\":\"l753bf282\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"备注\"},{\"name\":\"cdc4d06a\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"联系人QQ\"}]', NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\",\"children\":[{\"name\":\"id\",\"form_type\":\"int\",\"message\":\"自增ID\"}]},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]'),
(13, 11, '修改联系人', 1, 0, 'PUT', 'open/liaison/{id}', '[{\"name\":\"id\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"自增ID\"}]', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, '[{\"name\":\"liaison_job\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"联系人职位\"},{\"name\":\"liaison_name\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"联系人姓名\"},{\"name\":\"liaison_tel\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"联系电话\"},{\"name\":\"e06d7153\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"性别\"},{\"name\":\"e06d7152\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"联系人邮箱\"},{\"name\":\"e06d7159\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"联系人微信\"},{\"name\":\"l753bf282\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"备注\"},{\"name\":\"cdc4d06a\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"联系人QQ\"}]', NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\"},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]'),
(14, 11, '删除联系人', 1, 0, 'DELETE', 'open/liaison/{id}', '[{\"name\":\"id\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"自增ID\"}]', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, NULL, NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\"},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]'),
(15, 0, '发票记录', 0, 0, '0', '0', '', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, NULL, NULL, NULL),
(16, 15, '新增发票', 1, 0, 'POST', 'open/invoice', '', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, '[{\"name\":\"uid\",\"form_type\":\"int\",\"is_must\":false,\"message\":\"关联业务员id\"},{\"name\":\"bill_id\",\"form_type\":\"array\",\"is_must\":false,\"message\":\"关联付款单id\",\"symbol\":\"billId\"},{\"name\":\"eid\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"关联客戶id\",\"symbol\":\"customerList\"},{\"name\":\"cid\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"关联合同id\",\"symbol\":\"contractList\"},{\"name\":\"bill_date\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"期望开票日期\",\"symbol\":\"desireDate\"},{\"name\":\"collect_type\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"开票要求\",\"symbol\":\"invoicingMethod\"},{\"name\":\"collect_name\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"联系人\",\"symbol\":\"liaisonMan\"},{\"name\":\"collect_tel\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"联系电话\",\"symbol\":\"telephone\"},{\"name\":\"collect_email\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"邮箱地址\",\"symbol\":\"invoicingEmail\"},{\"name\":\"mail_address\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"邮寄地址\",\"symbol\":\"mailingAddress\"},{\"name\":\"types\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"发票类型\",\"symbol\":\"invoiceType\"},{\"name\":\"amount\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"开票金额（元）\",\"symbol\":\"invoiceAmount\"},{\"name\":\"price\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"付款单金额（元）\",\"symbol\":\"billAmount\"},{\"name\":\"title\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"发票抬头\",\"symbol\":\"invoiceHeader\"},{\"name\":\"ident\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"纳税人识别号\",\"symbol\":\"dutyParagraph\"},{\"name\":\"mark\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"备注\",\"symbol\":\"remark\"}]', NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\",\"children\":[{\"name\":\"id\",\"form_type\":\"int\",\"message\":\"自增ID\"}]},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]'),
(17, 15, '发票作废', 1, 0, 'PUT', 'open/invoice/{id}/invalid', '[{\"name\":\"id\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"自增ID\"}]', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, '[{\"name\":\"uid\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"业务员id\"},{\"name\":\"remark\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"作废原因\"}]', NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\"},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]'),
(18, 0, '客户账目记录', 0, 0, '0', '0', '', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, NULL, NULL, NULL),
(19, 18, '新增账目回款', 1, 0, 'POST', 'open/bill/payment', '', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, '[{\"name\":\"uid\",\"form_type\":\"int\",\"is_must\":false,\"message\":\"关联业务员id\"},{\"name\":\"cid\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"关联合同id\",\"symbol\":\"contractList\"},{\"name\":\"bill_cate_id\",\"form_type\":\"array\",\"is_must\":true,\"message\":\"财务收入科目id\",\"symbol\":\"incomeCategories\"},{\"name\":\"type_id\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"支付方式id\",\"symbol\":\"payType\"},{\"name\":\"num\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"回款金额（元）\",\"symbol\":\"collectionAmount\"},{\"name\":\"date\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"付款时间\",\"symbol\":\"payTime\"},{\"name\":\"attach\",\"form_type\":\"array\",\"is_must\":false,\"message\":\"付款凭证id\",\"symbol\":\"paymentVoucher\"},{\"name\":\"mark\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"备注\",\"symbol\":\"remark\"}]', NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\",\"children\":[{\"name\":\"id\",\"form_type\":\"int\",\"message\":\"自增ID\"}]},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]'),
(20, 18, '新增账目续费', 1, 0, 'POST', 'open/bill/renewal', '', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, '[{\"name\":\"uid\",\"form_type\":\"int\",\"is_must\":false,\"message\":\"关联业务员id\"},{\"name\":\"cid\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"关联合同id\",\"symbol\":\"contractList\"},{\"name\":\"bill_cate_id\",\"form_type\":\"array\",\"is_must\":true,\"message\":\"财务收入科目id\",\"symbol\":\"incomeCategories\"},{\"name\":\"cate_id\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"续费类型id\",\"symbol\":\"renewalType\"},{\"name\":\"type_id\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"支付方式id\",\"symbol\":\"payType\"},{\"name\":\"num\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"续费金额（元）\",\"symbol\":\"renewalAmount\"},{\"name\":\"date\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"付款时间\",\"symbol\":\"payTime\"},{\"name\":\"end_date\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"续费结束日期\",\"symbol\":\"renewalEndTime\"},{\"name\":\"attach\",\"form_type\":\"array\",\"is_must\":false,\"message\":\"付款凭证id\",\"symbol\":\"paymentVoucher\"},{\"name\":\"mark\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"备注\",\"symbol\":\"remark\"}]', NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\",\"children\":[{\"name\":\"id\",\"form_type\":\"int\",\"message\":\"自增ID\"}]},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]'),
(21, 18, '新增账目支出', 1, 0, 'POST', 'open/bill/expend', '', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, '[{\"name\":\"uid\",\"form_type\":\"int\",\"is_must\":false,\"message\":\"关联业务员id\"},{\"name\":\"cid\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"关联合同id\",\"symbol\":\"contractList\"},{\"name\":\"bill_cate_id\",\"form_type\":\"array\",\"is_must\":true,\"message\":\"财务支出科目id\",\"symbol\":\"expenditureCategories\"},{\"name\":\"type_id\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"支付方式id\",\"symbol\":\"payType\"},{\"name\":\"num\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"支出金额（元）\",\"symbol\":\"expenditureAmount\"},{\"name\":\"date\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"付款时间\",\"symbol\":\"payTime\"},{\"name\":\"attach\",\"form_type\":\"array\",\"is_must\":false,\"message\":\"付款凭证id\",\"symbol\":\"paymentVoucher\"},{\"name\":\"mark\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"备注\",\"symbol\":\"remark\"}]', NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\",\"children\":[{\"name\":\"id\",\"form_type\":\"int\",\"message\":\"自增ID\"}]},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]'),
(22, 18, '删除账目', 1, 0, 'DELETE', 'open/bill/{id}', '[{\"name\":\"id\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"自增ID\"}]', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, NULL, NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\"},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]'),
(23, 18, '新增付款提醒', 1, 0, 'POST', 'open/bill/remind', '', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, '[{\"name\":\"types\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"提醒类型\"},{\"name\":\"eid\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"关联客户id\"},{\"name\":\"cid\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"关联合同id\"},{\"name\":\"num\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"金额(元)\"},{\"name\":\"time\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"提醒日期\"},{\"name\":\"mark\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"提醒内容\"}]', NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\",\"children\":[{\"name\":\"id\",\"form_type\":\"int\",\"message\":\"自增ID\"}]},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]'),
(24, 0, '日程待办', 0, 0, '0', '0', '', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, NULL, NULL, NULL),
(25, 24, '新增日程', 1, 0, 'POST', 'open/schedule', '', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, '[{\"name\":\"uid\",\"form_type\":\"int\",\"is_must\":false,\"message\":\"关联业务员id\"},{\"name\":\"title\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"待办标题\"},{\"name\":\"member\",\"form_type\":\"array\",\"is_must\":true,\"message\":\"参与人id\"},{\"name\":\"start_time\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"开始时间\"},{\"name\":\"end_time\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"结束时间\"},{\"name\":\"all_day\",\"form_type\":\"int\",\"is_must\":false,\"message\":\"是否全天\"},{\"name\":\"period\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"重复周期\"},{\"name\":\"days\",\"form_type\":\"array\",\"is_must\":true,\"message\":\"重复周期为周\\/月时的重复频率\"},{\"name\":\"rate\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"重复频率\"},{\"name\":\"remind\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"是否提醒\"},{\"name\":\"type\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"操作方式\"},{\"name\":\"fail_time\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"重复截至日期\"}]', NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\",\"children\":[{\"name\":\"id\",\"form_type\":\"int\",\"message\":\"自增ID\"}]},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]'),
(26, 24, '修改日程', 1, 0, 'PUT', 'open/schedule/{id}', '[{\"name\":\"id\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"自增ID\"}]', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, '[{\"name\":\"title\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"待办标题\"},{\"name\":\"member\",\"form_type\":\"array\",\"is_must\":true,\"message\":\"参与人id\"},{\"name\":\"start_time\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"开始时间\"},{\"name\":\"end_time\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"结束时间\"},{\"name\":\"start\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"开始时间\"},{\"name\":\"end\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"结束时间\"},{\"name\":\"all_day\",\"form_type\":\"int\",\"is_must\":false,\"message\":\"是否全天\"},{\"name\":\"period\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"重复周期\"},{\"name\":\"days\",\"form_type\":\"array\",\"is_must\":true,\"message\":\"重复周期为周\\/月时的重复频率\"},{\"name\":\"rate\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"重复频率\"},{\"name\":\"remind\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"是否提醒\"},{\"name\":\"type\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"操作方式\"},{\"name\":\"fail_time\",\"form_type\":\"string\",\"is_must\":false,\"message\":\"重复截至日期\"}]', NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\"},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]'),
(27, 24, '删除日程', 1, 0, 'DELETE', 'open/schedule/{id}', '[{\"name\":\"id\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"自增ID\"}]', '2024-11-06 09:41:26', '2024-11-06 09:41:26', NULL, '[{\"name\":\"start\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"开始时间\"},{\"name\":\"end\",\"form_type\":\"string\",\"is_must\":true,\"message\":\"结束时间\"},{\"name\":\"type\",\"form_type\":\"int\",\"is_must\":true,\"message\":\"操作方式\"}]', NULL, '[{\"name\":\"data\",\"form_type\":\"array\",\"message\":\"数据\"},{\"name\":\"status\",\"form_type\":\"int\",\"message\":\"状态\"},{\"name\":\"message\",\"form_type\":\"string\",\"message\":\"说明\"}]');

SELECT `id` INTO @developId FROM `eb_system_menus` WHERE `unique_auth` = 'menus65e51ff04a5d5';
INSERT INTO `eb_system_menus` (`id`, `pid`, `icon`, `menu_name`, `api`, `methods`, `unique_auth`, `menu_path`, `menu_type`, `crud_id`, `uni_path`, `uni_img`, `position`, `path`, `component`, `level`, `other`, `sort`, `entid`, `type`, `is_show`, `status`, `created_at`, `updated_at`, `deleted_at`) VALUES
(NULL, @developId, '', '对外接口', '', '', 'menus67244e5243d58', '/develop/foreign', 0, 0, '', '', 0, '614', '', 1, '', 0, 0, 'M', 1, 1, '2024-09-27 11:23:39', '2024-11-01 11:43:37', NULL);
SELECT @foreignId := LAST_INSERT_ID();

INSERT INTO `eb_system_menus` (`id`, `pid`, `icon`, `menu_name`, `api`, `methods`, `unique_auth`, `menu_path`, `menu_type`, `crud_id`, `uni_path`, `uni_img`, `position`, `path`, `component`, `level`, `other`, `sort`, `entid`, `type`, `is_show`, `status`, `created_at`, `updated_at`, `deleted_at`) VALUES
(NULL, @foreignId, '', '接口文档', '', '', 'menus66f62f7db7ad3', '/develop/foreign/document', 0, 0, '', '', 0, '614/626', 'develop/foreign/document', 2, '', 0, 0, 'M', 1, 1, '2024-09-27 12:07:25', '2024-11-01 11:43:37', NULL),
(NULL, @foreignId, '', '授权密钥', '', '', 'menus66f8f51ea2940', '/develop/foreign/index', 0, 0, '', '', 0, '614/626', 'develop/foreign/index', 2, '', 0, 0, 'M', 1, 1, '2024-09-27 11:29:35', '2024-11-01 11:43:37', NULL);
