-- # 数据字典
INSERT INTO `eb_dict_type` (`id`, `name`, `ident`, `link_type`, `level`, `status`, `is_default`) VALUES (NULL, '商机类型', 'odds_type', 'custom', 1, 1, 0);
INSERT INTO `eb_dict_type` (`id`, `name`, `ident`, `link_type`, `level`, `status`, `is_default`) VALUES (NULL, '商机状态', 'odds_status', 'custom', 1, 1, 0);
SELECT @foreignId := LAST_INSERT_ID();
INSERT INTO `eb_dict_data` (`id`, `name`, `value`, `pid`, `type_id`, `type_name`, `level`, `sort`, `color`, `status`, `is_default`, `mark`, `created_at`, `updated_at`) VALUES
(NULL, '进行中', '1', '', @foreignId, 'odds_status', 1, 9, '#303133', 1, 0, '', '2025-08-01 08:39:04', '2025-08-20 08:02:41'),
(NULL, '赢单', '2', '', @foreignId, 'odds_status', 1, 7, '#303133', 1, 0, '', '2025-08-01 08:39:13', '2025-08-21 01:32:11'),
(NULL, '输单', '3', '', @foreignId, 'odds_status', 1, 5, '#303133', 1, 0, '', '2025-08-01 08:39:21', '2025-08-21 01:32:16'),
(NULL, '无效', '4', '', @foreignId, 'odds_status', 1, 0, '#303133', 1, 0, '', '2025-08-01 08:39:27', '2025-08-01 08:39:27');

INSERT INTO `eb_dict_type` (`id`, `name`, `ident`, `link_type`, `level`, `status`, `is_default`) VALUES (NULL, '线索来源', 'clue_way', 'custom', 1, 1, 0);
SELECT @foreignId := LAST_INSERT_ID();
INSERT INTO `eb_dict_data` (`id`, `name`, `value`, `pid`, `type_id`, `type_name`, `level`, `sort`, `color`, `status`, `is_default`, `mark`, `created_at`, `updated_at`) VALUES
(NULL, '企微', 'wework', '', @foreignId, 'clue_way', 1, 0, '#303133', 1, 0, '', '2025-08-20 07:12:47', '2025-08-20 07:12:47');

INSERT INTO `eb_dict_type` (`id`, `name`, `ident`, `link_type`, `level`, `status`, `is_default`) VALUES (NULL, '线索状态', 'clue_status', 'custom', 1, 1, 0);
SELECT @foreignId := LAST_INSERT_ID();
INSERT INTO `eb_dict_data` (`id`, `name`, `value`, `pid`, `type_id`, `type_name`, `level`, `sort`, `color`, `status`, `is_default`, `mark`, `created_at`, `updated_at`) VALUES
(NULL, '开启', '1', '', @foreignId, 'clue_status', 1, 0, '#36BC1F', 1, 0, '', '2025-07-26 08:52:44', '2025-08-07 09:52:39'),
(NULL, '关闭', '2', '', @foreignId, 'clue_status', 1, 0, '#303133', 1, 0, '', '2025-07-26 08:52:51', '2025-08-07 09:52:45');

INSERT INTO `eb_dict_type` (`id`, `name`, `ident`, `link_type`, `level`, `status`, `is_default`) VALUES (NULL, '产品类型', 'product_type', 'custom', 1, 1, 0);
INSERT INTO `eb_dict_type` (`id`, `name`, `ident`, `link_type`, `level`, `status`, `is_default`) VALUES (NULL, '产品状态', 'product_status', 'custom', 1, 1, 0);
SELECT @foreignId := LAST_INSERT_ID();
INSERT INTO `eb_dict_data` (`id`, `name`, `value`, `pid`, `type_id`, `type_name`, `level`, `sort`, `color`, `status`, `is_default`, `mark`, `created_at`, `updated_at`) VALUES
(NULL, '上架', '1', '', @foreignId, 'product_status', 1, 99, '#1F5DD9', 1, 0, '', '2025-07-30 02:06:11', '2025-08-21 01:31:45'),
(NULL, '下架', '2', '', @foreignId, 'product_status', 1, 0, '#E7631C', 1, 0, '', '2025-07-30 02:06:17', '2025-08-07 09:10:30');

-- # 线索
INSERT INTO `eb_form_cate` (`id`, `title`, `sort`, `types`, `status`, `ident`) VALUES (NULL, '基本信息', 1, 4, 1, '');
SELECT @foreignId := LAST_INSERT_ID();
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'name', '线索名称', 'text', 'input', @foreignId, '', 0, 0, 1, '请输入线索名称', 255, 1, '', '', 0, 'desc', 0, '', 10, 1, '4');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'source', '线索来源', 'single', 'select', @foreignId, '', 0, 0, 1, '请选择线索来源', 255, 1, 'clue_way', '', 0, '', 0, '', 9, 1, '4');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'phone', '联系电话', 'text', 'input', @foreignId, '', 0, 0, 0, '请输入联系电话', 255, 1, '', '', 0, '', 0, '', 5, 1, '4');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'area_cascade', '省市区', 'single', 'select', @foreignId, '', 0, 0, 0, '请选择省市区', 50, 1, 'area_cascade', '', 0, '', 0, '', 3, 1, '4');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'address', '详细地址', 'text', 'input', @foreignId, '', 0, 0, 0, '请输入详细地址', 50, 1, '', '', 0, '', 0, '', 2, 1, '4');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'status', '线索状态', 'radio', 'radio', @foreignId, '', 0, 0, 0, '请选择线索状态', 255, 1, 'clue_status', '1', 0, '', 0, '', 4, 1, '4');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'followed', '是否关注', 'radio', 'radio', @foreignId, '', 0, 0, 0, '是否关注', 5, 1, 'follow_status', '1', 0, '', 0, '', 1, 1, '4');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'customer_label', '客户标签', 'checked', 'checked', @foreignId, '', 0, 0, 0, '请选择客户标签', 50, 1, '', '', 0, '', 4, '', 8, 1, '4');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'createtime', '线索时间', 'datetime', 'datetime', @foreignId, '', 0, 0, 0, '请选择线索时间', 0, 0, '', '', 0, '', 4, '', 7, 1, '4');

INSERT INTO `eb_form_cate` (`id`, `title`, `sort`, `types`, `status`, `ident`) VALUES (NULL, '备注信息', 0, 4, 1, '');
SELECT @foreignId := LAST_INSERT_ID();
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'mark', '备注', 'textarea', 'input', @foreignId, '', 0, 0, 0, '请填写备注', 255, 1, '', '', 0, '', 0, '', 1, 1, '4');
-- # 商机
INSERT INTO `eb_form_cate` (`id`, `title`, `sort`, `types`, `status`, `ident`) VALUES (NULL, '基本信息', 1, 5, 1, '');
SELECT @foreignId := LAST_INSERT_ID();
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'name', '商机名称', 'text', 'input', @foreignId, '', 0, 0, 1, '请输入商机名称', 255, 1, '', '', 0, 'desc', 0, '', 7, 1, '5');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'eid', '客户名称', 'single', 'select', @foreignId, '', 0, 0, 1, '请选择客户/线索', 255, 1, '', '', 0, 'desc', 0, '', 6, 1, '5');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'types', '商机类型', 'single', 'select', @foreignId, '', 0, 0, 0, '请选择商机类型', 255, 1, 'odds_type', '', 0, '', 0, '', 5, 1, '5');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'status', '商机状态', 'radio', 'radio', @foreignId, '', 0, 0, 1, '请选择商机状态', 255, 1, 'odds_status', '1', 0, '', 0, '', 4, 1, '5');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'followed', '是否关注', 'radio', 'radio', @foreignId, '', 0, 0, 0, '是否关注', 5, 1, 'follow_status', '1', 0, '', 0, '', 3, 1, '5');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'description', '商机描述', 'textarea', 'input', @foreignId, '', 0, 0, 0, '请填写商机描述', 255, 1, '', '', 0, '', 0, '', 2, 1, '5');

INSERT INTO `eb_form_cate` (`id`, `title`, `sort`, `types`, `status`, `ident`) VALUES (NULL, '产品清单', 0, 5, 1, 'product');
-- # 产品
INSERT INTO `eb_form_cate` (`id`, `title`, `sort`, `types`, `status`, `ident`) VALUES (NULL, '产品信息', 1, 6, 1, '');
SELECT @foreignId := LAST_INSERT_ID();
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'name', '产品名称', 'text', 'input', @foreignId, '', 0, 0, 1, '请输入产品名称', 255, 1, '', '', 0, 'desc', 0, '', 8, 1, '6');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'path', '产品分类', 'single', 'select', @foreignId, '', 0, 0, 1, '请选择产品分类', 255, 1, '', '', 0, '', 0, '', 7, 1, '6');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'unit_name', '单位名', 'text', 'input', @foreignId, '', 0, 0, 1, '请输入单位名', 255, 1, '', '', 0, '', 0, '', 6, 1, '6');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'types', '产品类型', 'radio', 'radio', @foreignId, '', 0, 0, 1, '请选择产品类型', 255, 1, 'product_type', '1', 0, '', 0, '', 5, 1, '6');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'number', '产品编号', 'text', 'input', @foreignId, '', 0, 0, 1, '请输入产品编号', 255, 1, '', '', 0, '', 0, '', 4, 1, '6');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'is_show', '产品状态', 'radio', 'radio', @foreignId, '', 0, 0, 1, '请输入产品编号', 255, 1, 'product_status', '1', 0, '', 0, '', 3, 1, '6');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'description', '产品简介', 'oaWangeditor', 'oaWangeditor', @foreignId, '', 0, 0, 0, '请输入产品简介', 1, 1, '', '', 0, '', 0, '', 2, 1, '6');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'sort', '排序', 'number', 'input', @foreignId, '', 0, 0, 0, '', 10, 1, '', '', 0, '', 0, '', 1, 1, '6');

INSERT INTO `eb_form_cate` (`id`, `title`, `sort`, `types`, `status`, `ident`) VALUES (NULL, '产品清单', 0, 2, 1, 'product');
INSERT INTO `eb_form_cate` (`id`, `title`, `sort`, `types`, `status`, `ident`) VALUES (NULL, '库存定价', 0, 6, 1, 'product');

INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'oid', '商机编号', 'single', 'select', 3, '', 0, 0, 0, '请选择商机编号', 10, 1, '', '', 0, '', 0, '', 6, 1, '2');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'eid', '客户名称', 'single', 'select', 5, '', 0, 0, 0, '请选择客户', 1, 1, '', '', 0, '', 6, '', 4, 1, '3');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'clue_id', '关联线索', 'single', 'select', 1, '', 0, 0, 0, '请输入线索名称', 10, 1, '', '', 0, '', 0, '', 6, 1, '1');
INSERT INTO `eb_form_data` (`id`, `key`, `key_name`, `type`, `input_type`, `cate_id`, `param`, `decimal_place`, `upload_type`, `required`, `placeholder`, `max`, `min`, `dict_ident`, `value`, `uniqued`, `desc`, `link_type`, `link_field`, `sort`, `status`, `types`) VALUES (NULL, 'member', '协作者', 'multipleMember', 'member', 1, '', 0, 0, 0, '', 10, 1, '', '', 0, '', 0, '', 1, 1, '1');
