<?php

declare(strict_types=1);


namespace App\Http\Model\Message;

use App\Http\Model\Admin\Admin;
use App\Http\Model\Company\Company;
use App\Http\Service\Notice\NoticeRecordService;
use crmeb\basic\BaseModel;
use crmeb\traits\model\TimeDataTrait;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\HasOne;

/**
 * 企业消息
 * Class MessageNotice.
 */
class MessageNotice extends BaseModel
{
    use TimeDataTrait;

    /**
     * 自动写入时间戳.
     * @var bool
     */
    public $timestamps = false;

    /**
     * 表名.
     * @var string
     */
    protected $table = 'enterprise_message_notice';

    /**
     * 主键.
     * @var string
     */
    protected $primaryKey = 'id';

    protected $casts = [
        'id'          => 'integer',
        'entid'       => 'integer',
        'send_id'     => 'integer',
        'type'        => 'integer',
        'cate_id'     => 'integer',
        'message_id'  => 'integer',
        'is_read'     => 'integer',
        'is_handle'   => 'integer',
        'is_show'     => 'integer',
        'link_id'     => 'integer',
        'link_status' => 'integer',
        'created_at'  => 'datetime:Y-m-d H:i:s',
        'updated_at'  => 'datetime:Y-m-d H:i:s',
    ];

    /**
     * 一对一关联企业.
     * @return HasOne
     */
    public function enterprise()
    {
        return $this->hasOne(Company::class, 'id', 'entid');
    }

    /**
     * 一对一关联用户.
     * @return HasOne
     */
    public function user()
    {
        return $this->hasOne(Admin::class, 'id', 'to_uid');
    }

    public function scopeIds($query, $value)
    {
        $query->whereIn('id', $value);
    }

    /**
     * @param mixed $value
     * @return array|mixed
     */
    public function getButtonTemplateAttribute($value)
    {
        return $value ? json_decode($value, true) : null;
    }

    public function setButtonTemplateAttribute($value)
    {
        $this->attributes['button_template'] = json_encode($value);
    }

    /**
     * @param mixed $value
     * @return array|mixed
     */
    public function getOtherAttribute($value)
    {
        return $value ? json_decode($value, true) : null;
    }

    public function setOtherAttribute($value)
    {
        $this->attributes['other'] = json_encode($value);
    }

    public function scopeUid($query, $value)
    {
        is_array($value) ? $query->whereIn('to_uid', $value) : $query->where('to_uid', $value);
    }

    public function scopeOtherId($query, $value)
    {
        if ($value !== '') {
            $query->where('other->id', $value);
        }
    }

    public function scopeLinkId($query, $value)
    {
        if (is_array($value)) {
            $query->where('link_id', $value);
        } elseif ($value !== '') {
            $query->where('link_id', $value);
        }
    }

    public function scopeTemplateType($query, $value)
    {
        if (is_array($value)) {
            $query->whereIn('template_type', $value);
        } else {
            $query->where('template_type', $value);
        }
    }

    /**
     * 消息类型作用域
     * @param Builder $query
     * @param mixed $value
     */
    public function scopeCateId($query, $value)
    {
        is_array($value) ? $query->whereIn('cate_id', $value) : $query->where('cate_id', $value);
    }

    public function scopeToUid($query, $value)
    {
        if (is_array($value)) {
            $query->whereIn('to_uid', $value);
        } else {
            $query->where('to_uid', uid_to_uuid($value))->orWhere('to_uid', $value);
        }
    }

    /**
     * 关联查询消息模板
     */
    public function template(): HasOne
    {
        return $this->hasOne(MessageTemplate::class, 'message_id', 'message_id')->where('type', 0);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::updated(function ($model) {
            if ($model->isDirty('is_read')) {
                app(NoticeRecordService::class)->updatePushBadge($model->user_id);
            }
        });
    }
}
