/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatLanguageSelect: typeof import('./../components/chat-sidebar/chat-language-select.vue')['default']
    ChatLogin: typeof import('./../components/chat-login/chat-login.vue')['default']
    ChatLoginBase: typeof import('./../components/chat-login/chat-login-base.vue')['default']
    ChatMainContainer: typeof import('./../components/chat-main-container/chat-main-container.vue')['default']
    ChatMainTopbar: typeof import('./../components/chat-main-container/chat-main-topbar.vue')['default']
    ChatMarkdown: typeof import('./../components/chat-markdown/chat-markdown.vue')['default']
    ChatMessageAi: typeof import('./../components/chat-messages/chat-message-ai.vue')['default']
    ChatMessageIndex: typeof import('./../components/chat-message-input/chat-message-index.vue')['default']
    ChatMessageInput: typeof import('./../components/chat-message-input/chat-message-input.vue')['default']
    ChatMessages: typeof import('./../components/chat-messages/chat-messages.vue')['default']
    ChatMessageSendBtn: typeof import('./../components/chat-message-input/chat-message-send-btn.vue')['default']
    ChatMessageSuggestion: typeof import('./../components/chat-messages/chat-message-suggestion.vue')['default']
    ChatMessageTable: typeof import('./../components/chat-messages/chat-message-table.vue')['default']
    ChatMessageToolbar: typeof import('./../components/chat-message-input/chat-message-toolbar.vue')['default']
    ChatMessageTools: typeof import('./../components/chat-messages/chat-message-tools.vue')['default']
    ChatMessageUpload: typeof import('./../components/chat-message-input/chat-message-upload.vue')['default']
    ChatMessageUser: typeof import('./../components/chat-messages/chat-message-user.vue')['default']
    ChatSidebar: typeof import('./../components/chat-sidebar/chat-sidebar.vue')['default']
    ChatSidebarApps: typeof import('./../components/chat-sidebar/chat-sidebar-apps.vue')['default']
    ChatSidebarIndex: typeof import('./../components/chat-sidebar/chat-sidebar-index.vue')['default']
    ChatSidebarMobile: typeof import('./../components/chat-sidebar/chat-sidebar-mobile.vue')['default']
    ChatSidebarRecentChat: typeof import('./../components/chat-sidebar/chat-sidebar-recent-chat.vue')['default']
    ChatSidebarUserinfo: typeof import('./../components/chat-sidebar/chat-sidebar-userinfo.vue')['default']
    ChatWelcome: typeof import('./../components/chat-welcome/chat-welcome.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IEpArrowRight: typeof import('~icons/ep/arrow-right')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    IEpOperation: typeof import('~icons/ep/operation')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
