<?php

declare(strict_types=1);


namespace App\Http\Model\Storage;

use crmeb\basic\BaseModel;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Cache;

/**
 * 物资分类.
 *
 * Class StorageCategory.
 */
class StorageCategory extends BaseModel
{
    protected $primaryKey = 'id';

    protected $casts = [
        'id'         => 'integer',
        'pid'        => 'integer',
        'sort'       => 'integer',
        'level'      => 'integer',
        'type'       => 'integer',
        'entid'      => 'integer',
        'created_at' => 'datetime:Y-m-d H:i:s',
        'updated_at' => 'datetime:Y-m-d H:i:s',
    ];

    protected $table = 'storage_category';

    /**
     * path修改器.
     */
    public function setPathAttribute($value)
    {
        $this->attributes['path'] = $value ? implode('/', $value) : '';
    }

    /**
     * path获取器.
     * @return false|string[]
     */
    public function getPathAttribute($value)
    {
        return $value ? array_map('intval', explode('/', $value)) : [];
    }

    /**
     * 分类类型作用域
     * @param Builder $query
     * @return Builder
     */
    public function scopeType($query, $value)
    {
        return $query->where('type', $value);
    }

    /**
     * 企业ID作用域
     * @param Builder $query
     * @return Builder
     */
    public function scopeEntid($query, $value)
    {
        if ($value !== '') {
            $query->where('entid', $value);
        }
    }

    /**
     * 企业ID作用域
     * @param Builder $query
     * @return Builder
     */
    public function scopeNameLike($query, $value)
    {
        return $value !== '' ? $query->where('cate_name', 'LIKE', "%{$value}%") : null;
    }

    /**
     * ID作用域
     * @param Builder $query
     * @return Builder
     */
    public function scopeNotId($query, $value)
    {
        is_array($value) ? $query->whereNotIn('id', $value) : $query->where('id', '!=', $value);
    }

    /**
     * 作用域
     * @param Builder $query
     * @return Builder
     */
    public function scopeCateName($query, $value)
    {
        if ($value !== '') {
            $query->where('cate_name', $value);
        }
    }

    /**
     * 作用域
     * @param Builder $query
     * @return Builder
     */
    public function scopePid($query, $value)
    {
        if ($value !== '') {
            is_array($value) ? $query->whereIn('pid', $value) : $query->where('pid', $value);
        }
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::saved(function ($data) {
            Cache::tags(['storage_cate_' . $data->entid, 'storage_record_list_' . $data->entid])->flush();
        });
    }
}
